### ISSUE TITLE
"Nondebug" compile problem

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiog#2]
Many errors due to not declared "disjointRects" such as:
>from /home/alexey/dev/src/kiog/src/Og/Gorilla/RectPacking/GuillotineBinPack.cpp:17:
>/home/alexey/dev/src/kiog/src/Og/Gorilla/RectPacking/GuillotineBinPack.cpp: In member function
>‘void GuillotineBinPack::Insert(std::vector<RectSize>&, std::vector<BPRect>&, bool,
>GuillotineBinPack::FreeRectChoiceHeuristic, GuillotineBinPack::GuillotineSplitHeuristic)’:
>/home/alexey/dev/src/kiog/src/Og/Gorilla/RectPacking/GuillotineBinPack.cpp:135:10: error:
>‘disjointRects’ was not declared in this scope
>   assert(disjointRects.Add(newNode) == true);
>          ^

It's declared if and only if _DEBUG defined
> #ifdef _DEBUG
>	/// Used to track that the packer produces proper packings.
>	DisjointRectCollection disjointRects;
> #endif

But used in many places without such ifdef construction:
>assert(disjointRects.Add(newNode) == true);

Looks like this code has been never built in Release

Regards, Alexey Knyshev

**Comment by novembermonk** [comment]
Normally, assert gets expanded to a no-op if NDEBUG is defined.
So this should compile. Why doesn't it ? Is NDEBUG not defined ?

**Comment by novembermonk** [comment]
Should be fixed in bdadb84
